//export all of the types of action

///LOGIN
export const LOGIN = 'LOGIN';
export const SET_LOGIN_PENDING = 'SET_LOGIN_PENDING';
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS';
export const SET_LOGIN_ERROR = 'SET_LOGIN_ERROR';
export const SET_LOGIN_CANCEL = 'SET_LOGIN_CANCEL';

///NICKNAME
export const SET_NICKNAME_SUCCESS = 'SET_NICKNAME_SUCCESS';
export const SET_NICKNAME_ERROR = 'SET_NICKNAME_ERROR';
export const SET_NICKNAME_PENDING = 'SET_NICKNAME_PENDING';
export const SET_CHANGE_TEXT_VALIDE = 'SET_CHANGE_TEXT_VALIDE';
export const SET_CHANGE_TEXT_INVALIDE = 'SET_CHANGE_TEXT_INVALIDE';

//PROFILE
export const GET_CURRENT_USER = 'SET_CURRENT_USER';

