//export all of the types of action
///NICKNAME
export const SET_NICKNAME_SUCCESS = 'SET_NICKNAME_SUCCESS';
export const SET_NICKNAME_ERROR = 'SET_NICKNAME_ERROR';
export const SET_NICKNAME_PENDING = 'SET_NICKNAME_PENDING';
export const SET_CHANGE_TEXT_VALIDE = 'SET_CHANGE_TEXT_VALIDE';
export const SET_CHANGE_TEXT_INVALIDE = 'SET_CHANGE_TEXT_INVALIDE';
